#name: "Sphinx: Render docs"
#
#on: push
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#    - uses: actions/checkout@v4
#    - name: Build HTML
#      uses: ammaraskar/sphinx-action@master
#    - name: Upload artifacts
#      uses: actions/upload-artifact@v4
#      with:
#        name: html-docs
#        path: docs/_build/html/
#    - name: Deploy
#      uses: peaceiris/actions-gh-pages@v4
#      #if: github.ref == 'refs/heads/main'
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: docs/_build/html
name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master, gh-pages-docs] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@3.1